version: '3'

services:
  mysql:
    image: mysql:8.0.31
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '${MYSQL_PORT}:3306'
    expose:
      - '3306'
    networks:
      - internalnet
    environment:
      - 'MYSQL_DATABASE=${MYSQL_DATABASE}'
      - 'MYSQL_USER=${MYSQL_USER}'
      - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
      - 'MYSQL_RANDOM_ROOT_PASSWORD=yes'
      - 'SERVICE_NAME=mysql'
      - 'SERVICE_TAGS=prod'
  wordpress:
    image: wordpress:6.1.1-php8.0-apache
    restart: always
    volumes:
      - ./html:/var/www/html
    ports:
      - '${SERVER_PORT}:80'
    expose:
      - '${SERVER_PORT}'
    depends_on:
      - mysql
    networks:
      - internalnet
    environment:
      - 'WORDPRESS_DB_HOST=mysql'
      - 'WORDPRESS_DB_NAME=${MYSQL_DATABASE}'
      - 'WORDPRESS_DB_USER=${MYSQL_USER}'
      - 'WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}'
      - 'SERVICE_NAME=lockey'
      - 'SERVICE_TAGS=prod'

networks:
  internalnet:
    driver: bridge